name: Example workflow for ServiceNow using Snyk
on: 
 workflow_dispatch:
    inputs:
      RunScript:
        description: "To run codescan"
        required: true
        default: 'false'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Snyk CLI
        run: |
          curl -o- https://snyk.io/install.sh | bash
          export PATH=$HOME/.snyk/bin:$PATH
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --file=path/to/javascript/files
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor ServiceNow Code
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
