name: Example workflow for ServiceNow using Snyk
on: 
 workflow_dispatch:
    inputs:
      RunScript:
        description: "To run codescan"
        required: true
        default: 'false'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@v3
        with:
          args: test --file=path/to/javascript/files
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor ServiceNow Code
        uses: snyk/actions@v3
        with:
          args: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
