name: "CodeQL2 for ServiceNow"

on:
   workflow_dispatch:
    inputs:
      RunScript:
        description: "To run codescan"
        required: true
        default: 'false'

jobs:
  analyze:
    name: Analyze (${ { matrix.language } })
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ "javascript-typescript" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }} # Use a PAT if accessing a different repo
          ref: master # Ensure this matches the correct branch

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: (${ { matrix.language } })
          queries: security-and-quality
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
