name: ServiceNow GitHub Actions Demo

on:
  push:
    branches:
      - development
      - master

jobs:
  build:
    name: Publish from Dev
    runs-on: ubuntu-latest

    steps:
      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@2.0.0
        env:
          nowUsername: ${{ secrets.SN_DEV_USERNAME }}
          nowPassword: ${{ secrets.SN_DEV_PASSWORD }}
          nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}

      - name: ServiceNow CI/CD Publish App
        id: publish_app
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.1
          versionFormat: template
        env:
          nowUsername: ${{ secrets.SN_DEV_USERNAME }}
          nowPassword: ${{ secrets.SN_DEV_PASSWORD }}
          nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}

      - name: Send Email Notification for Build
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build Job Completed"
          body: |
            The build job has completed successfully.
            Published version: ${{ steps.publish_app.outputs.newVersion }}
            Do not reply to mail. 
            This is an automated email from DevOps team. 
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}

    outputs:
      publishversion: ${{ steps.publish_app.outputs.newVersion }}

  deployprod:
    needs: build
    name: Deploy to Prod
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: ServiceNow CI/CD Install App
        id: install_app_prod
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.build.outputs.publishversion }}
        env:
          nowUsername: ${{ secrets.SN_PROD_USERNAME }}
          nowPassword: ${{ secrets.SN_PROD_PASSWORD }}
          nowInstallInstance: ${{ secrets.SN_PROD_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}

      - name: Send Email Notification for Deploy
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Job Completed"
          body: |
            The deployment job has completed successfully.
            Installed version: ${{ needs.build.outputs.publishversion }}
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}

