name: trivy

on:
  workflow_dispatch:
    inputs:
      RunScript:
        description: "To run codescan"
        required: true
        default: 'false'

permissions:
  contents: read

jobs:
  build:
    name: Trivy Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.45.0_Linux-64bit.tar.gz | tar xvz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy vulnerability scanner on files
        run: |
          trivy fs --severity CRITICAL,HIGH --output trivy-results.sarif --format sarif .

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
